# Generated by Django 5.2.15 on 2026-07-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_address_alter_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
