# Generated by Django 5.2.15 on 2026-08-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenantmembership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='Asia/Jakarta', max_length=64),
        ),
    ]
