# Generated by Django 5.2.15 on 2026-07-10 12:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PEND', 'Pending'), ('VOID', 'Void')], default='PEND', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product_name_at_transaction', models.CharField(max_length=150)),
                ('price_at_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
