# Generated by Django 5.2.15 on 2026-08-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderitem_remove_orderdetail_order_and_more"),
        ("products", "0003_product_created_at_product_is_archived_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="quantity_gte_0",
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="quantity_must_than_0"
            ),
        ),
    ]
