# Generated by Django 5.2.15 on 2026-08-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_quantity_gte_0_and_more'),
        ('products', '0005_alter_stockmovement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('VOID', 'Void')], default='PENDING', max_length=7),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_at_transaction__gte', 0)), name='price_cannot_be_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('sub_total__gte', 0)), name='sub_total_cannot_be_negative'),
        ),
    ]
