# Generated by Django 5.2.15 on 2026-08-10 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_created_at_product_is_archived_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('DEDUCT', 'Deduct')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('RESTOCK', 'Restock'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('SALE', 'Sale'), ('LOST', 'Lost'), ('ADJUSTMENT', 'Adjustment'), ('OTHER', 'Other')], max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='products.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_must_be_positive'), models.CheckConstraint(condition=models.Q(models.Q(('reason', 'OTHER'), _negated=True), models.Q(('notes', ''), _negated=True), _connector='OR'), name='notes_required_if_reason_other')],
            },
        ),
    ]
