# Generated by Django 5.2.15 on 2026-08-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
