# Generated by Django 5.2.15 on 2026-08-21 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('RESTOCK', 'Restock'), ('DAMAGED', 'Damaged'), ('EXPIRED', 'Expired'), ('SALE', 'Sale'), ('LOST', 'Lost'), ('VOID', 'Void'), ('ADJUSTMENT', 'Adjustment'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
